<div style="background-color:#EAF4EC; padding:20px; border-radius:10px;"> <h2 style="color:#2F6F4E; text-align:center; margin-bottom:5px;"> Data Loading </h2> <h4 style="color:#2F6F4E; text-align:center; margin-top:0;"> Master Thesis – ESG Governance Indicators (EU-27) </h4> <p style="font-size:14px; color:#2F6F4E;"> This notebook performs the <strong>initial data loading and structural inspection</strong> step of the CRISP-ML(Q) methodology.<br> The goal is to understand the composition, metadata, and structure of the raw ESG Governance datasets before EDA or preprocessing. </p> <p style="font-size:14px; color:#2F6F4E;"> Exploratory analysis will follow in <code>02_data_understanding_EDA.ipynb</code>, and cleaning will occur in <code>03_data_preprocessing.ipynb</code>. </p> </div>

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
BASE = Path("../../data/raw/ESG_CSV") 
esg_series = pd.read_csv(BASE / "ESGSeries.csv")
esg_data = pd.read_csv(BASE / "ESGCSV.csv")

display(esg_series.head())
display(esg_data.head())

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,AG.LND.AGRI.ZS,Environment: Food Security,Agricultural land (% of land area),NaN,Agricultural land refers to the share of land ...,% (share) of land area,Annual,NaN,Areas of former states are included in the suc...,Weighted average,The data are collected by the Food and Agricul...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Agriculture is still a major sect...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0
1,AG.LND.FRLS.HA,Environment: Natural capital endowment and man...,Tree Cover Loss,Identifies areas of gross tree cover loss.,"Shows year-by-year tree cover loss, defined as...",Hectares,Annual,NaN,Administrative boundaries: Global Administrati...,Weighted average,NaN,NaN,"In this data set, “tree cover” is defined as a...",Global Forest Watch. Tree Cover Loss (Hansen/U...,NaN,NaN,https://data.globalforestwatch.org/maps/gfw::t...,https://data.globalforestwatch.org/pages/data-...,NaN,CC BY-4.0
2,AG.LND.FRST.ZS,Environment: Natural capital endowment and man...,Forest area (% of land area),NaN,Forest area (% of land area) is the share of t...,% (share) of land area,Annual,NaN,The world and regional aggregate series do not...,Weighted average,FAO has been collecting and analyzing data on ...,NaN,NaN,"FAOSTAT, Food and Agriculture Organization of ...",Methodology: Forest is determined both by the ...,"As threats to biodiversity mount, the internat...",NaN,NaN,NaN,CC BY-4.0
3,AG.PRD.FOOD.XD,Environment: Food Security,Food production index (2014-2016 = 100),NaN,Food production index covers food crops that a...,index (2014-2016=100),Annual,2014-16,NaN,Weighted average,Agricultural data are collected by the Food an...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: The agricultural production index...,The commodities covered in the computation of ...,NaN,NaN,NaN,CC BY-4.0
4,CC.EST,Governance: Stability & Rule of Law,Control of Corruption: Estimate,NaN,Control of Corruption captures perceptions of ...,NaN,Annual,NaN,NaN,NaN,NaN,NaN,NaN,"Detailed documentation of the WGI, interactive...",NaN,NaN,NaN,NaN,NaN,CC BY-4.0

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,86.082150,86.321160,86.491156,86.583767,86.523897,86.527129,86.503099,86.347769,86.449919,NaN
1,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,88.406777,88.661643,89.186171,90.351067,88.689841,89.928996,90.241777,90.434095,90.654518,91.64543
2,Arab World,ARB,Adjusted savings: natural resources depletion ...,NY.ADJ.DRES.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.200009,6.245928,5.406433,6.465929,8.238448,7.278235,4.628360,NaN,NaN,NaN
3,Arab World,ARB,Adjusted savings: net forest depletion (% of GNI),NY.ADJ.DFOR.GN.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,0.078484,0.089821,0.087373,0.099548,0.054242,0.059945,0.071353,NaN,NaN,NaN
4,Arab World,ARB,Agricultural land (% of land area),AG.LND.AGRI.ZS,NaN,27.845967,27.83858,27.859229,27.863412,27.88415,...,39.838000,39.870863,39.936386,39.985215,39.970860,39.907787,39.968729,39.967337,40.875467,NaN

In [3]:
esg_series.shape
esg_data.shape
print("ESGSeries -> linhas:", esg_series.shape[0], " | colunas:", esg_series.shape[1])
print("ESGData   -> linhas:", esg_data.shape[0], " | colunas:", esg_data.shape[1])

ESGSeries -> linhas: 71  | colunas: 20
ESGData   -> linhas: 16969  | colunas: 68

In [4]:
# Existent topics 
esg_series["Topic"].unique()

array(['Environment: Food Security',
       'Environment: Natural capital endowment and management',
       'Governance: Stability & Rule of Law',
       'Social: Access to Services', 'Environment: Energy use & security',
       'Environment: Emissions & pollution',
       'Environment: Environment/climate risk & resilience', nan,
       'Governance: Innovation', 'Governance: Government Effectiveness',
       'Governance: Human Rights', 'Governance: Economic Environment',
       'Social: Education & skills', 'Governance: Gender',
       'Social: Health & Nutrition', 'Social: Poverty & Inequality',
       'Social: Employment', 'Social: Demography'], dtype=object)

#### Topic missing: is it a Governance Indicator?

In [5]:
esg_series["Topic"].isna().sum()

np.int64(1)

In [6]:
esg_series[esg_series["Topic"].isna()][["Series Code", "Indicator Name"]]

       Series Code                                     Indicator Name
28  ER.H2O.FWST.ZS  Level of water stress: freshwater withdrawal a...

ER.H2O.FWST.ZS – “Level of water stress: freshwater withdrawal as a % of available freshwater resources”
is indeed an environmental indicator (not governance-related).

In [7]:
# Correct the "Topic" issue 
esg_series.loc[esg_series["Series Code"]=="ER.H2O.FWST.ZS",
               "Topic"] = "Environment: Water Resources"

In [8]:
esg_series["Topic"].isna().sum()

np.int64(0)

In [9]:
# Filter Governance indicators
gov_series = esg_series[esg_series["Topic"].str.startswith("Governance", na=False)].copy()

print("Number of Governance Indicators:", gov_series["Series Code"].nunique())
display(gov_series[["Series Code", "Indicator Name", "Topic"]].sort_values("Indicator Name"))

Number of Governance Indicators: 18

,Series Code,Indicator Name,Topic
4,CC.EST,Control of Corruption: Estimate,Governance: Stability & Rule of Law
44,SD.ESR.PERF.XQ,Economic and Social Rights Performance Score,Governance: Human Rights
40,NY.GDP.MKTP.KD.ZG,GDP (annual % growth),Governance: Economic Environment
32,GE.EST,Government Effectiveness: Estimate,Governance: Government Effectiveness
36,IT.NET.USER.ZS,Individuals using the Internet (% of population),Governance: Economic Environment
64,SM.POP.NETM,Net migration,Governance: Stability & Rule of Law
35,IP.PAT.RESD,"Patent applications, residents",Governance: Innovation
41,PV.EST,Political Stability and Absence of Violence/Te...,Governance: Stability & Rule of Law
49,SG.GEN.PARL.ZS,Proportion of seats held by women in national ...,Governance: Gender
62,SL.TLF.CACT.FM.ZS,Ratio of female to male labor force participat...,Governance: Gender
43,RQ.EST,Regulatory Quality: Estimate,Governance: Government Effectiveness
31,GB.XPD.RSDV.GD.ZS,Research and development expenditure (% of GDP),Governance: Innovation
42,RL.EST,Rule of Law: Estimate,Governance: Stability & Rule of Law
46,SE.ENR.PRSC.FM.ZS,"School enrollment, primary and secondary (gros...",Governance: Gender
34,IP.JRN.ARTC.SC,Scientific and technical journal articles,Governance: Innovation
33,IC.LGL.CRED.XQ,Strength of legal rights index (0=weak to 12=s...,Governance: Human Rights
69,SP.UWT.TFRT,Unmet need for contraception (% of married wom...,Governance: Gender
70,VA.EST,Voice and Accountability: Estimate,Governance: Human Rights

Check this indicator: IC.LGL.CRED.XQ	Strength of legal rights index (0=weak to 12=s...	Governance: Human Rights

In [10]:
code_to_check = "IC.LGL.CRED.XQ"
subset = esg_data[esg_data["Indicator Code"] == code_to_check]

In [11]:
print(f"Number of indicator lines {code_to_check}: {subset.shape[0]}")
display(subset.head())

Number of indicator lines IC.LGL.CRED.XQ: 239

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
65,Arab World,ARB,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,1.476190,1.409091,1.409091,1.772727,2.363636,3.090909,NaN,NaN,NaN,NaN
136,Caribbean small states,CSS,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,NaN,NaN,NaN,NaN
207,Central Europe and the Baltics,CEB,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,NaN,NaN,NaN,NaN
278,Early-demographic dividend,EAR,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,3.901639,4.131148,4.262295,4.606557,4.819672,5.295082,NaN,NaN,NaN,NaN
349,East Asia & Pacific,EAS,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,NaN,NaN,NaN,NaN,NaN,NaN,...,6.241379,6.310345,6.551724,7.241379,7.241379,7.241379,NaN,NaN,NaN,NaN

During metadata validation, this indicator appeared under “Governance: Human Rights” in the ESG dataset.
However, this classification is inconsistent: it belongs to the World Development Indicators and measures credit market legal protection, not governance or human rights.
Therefore, it was excluded from the Governance dataset to maintain conceptual consistency.

In [12]:
# Exclude the indicator 
gov_series = gov_series[gov_series["Series Code"] != "IC.LGL.CRED.XQ"].copy()

In [13]:
print("Number of Governance Indicators:",
      gov_series["Series Code"].nunique())

Number of Governance Indicators: 17

<div style="background-color:#EAF4EC; padding:16px; border-radius:10px;">

<h2 style="color:#2F6F4E; margin-bottom:5px; font-size:20px;">
EU-27
</h2>

In [14]:
EU27_ISO3 = ["AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA",
    "DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD",
    "POL","PRT","ROU","SVK","SVN","ESP","SWE"]

In [15]:
EU27_NAMES = ["Austria","Belgium","Bulgaria","Croatia","Cyprus","Czechia","Denmark",
    "Estonia","Finland","France","Germany","Greece","Hungary","Ireland","Italy",
    "Latvia","Lithuania","Luxembourg","Malta","Netherlands","Poland","Portugal",
    "Romania","Slovak Republic","Slovenia","Spain","Sweden"]

In [16]:
country_col = "Country Name"
code_col = "Country Code"

In [17]:
esg_data["Country Name"].unique()

array(['Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD)', 'European Union',
       'Fragile and conflict affected situations',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & Caribbean (IDA & IBRD)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East, North Africa, Afghanistan & Pakistan',
       'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
       'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
       'Middle income', 'North America', 'OECD members',
       'Other small states', 'Pacific island small states',
       'Post-demographic dividend', 'Pre-demographic dividend',
       'Small states', 'South Asia', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD)', 'Upper middle income', 'World',
       'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kuwait',
       'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman',
       'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay',
       'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis',
       'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Yemen, Rep.', 'Zambia',
       'Zimbabwe'], dtype=object)

#### Is there any EU27 Country missing from the dataset?

In [18]:
present = sorted(set(esg_data["Country Name"]) & set(EU27_NAMES))
missing = [c for c in EU27_NAMES if c not in present]

print(f"EU-27 countries present ({len(present)}/{len(EU27_NAMES)}):")
print(present)
print()
print(f"Missing ({len(missing)}):")
print(missing)

EU-27 countries present (27/27):
['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovak Republic', 'Slovenia', 'Spain', 'Sweden']

Missing (0):
[]

In [19]:
EU27_ISO3 = [
    "AUT","BEL","BGR","HRV","CYP","CZE","DNK","EST","FIN","FRA",
    "DEU","GRC","HUN","IRL","ITA","LVA","LTU","LUX","MLT","NLD",
    "POL","PRT","ROU","SVK","SVN","ESP","SWE"
]

# Only Governance
esg_gov = esg_data[esg_data["Indicator Code"].isin(esg_data["Indicator Code"])]

# Indicator per country
coverage = (esg_gov.groupby("Country Code")["Indicator Code"].nunique().reset_index(name="num_indicators"))
coverage["expected"] = len(esg_data)
coverage["missing"] = coverage["expected"] - coverage["num_indicators"]

print(coverage.sort_values("missing", ascending=False))

    Country Code  num_indicators  expected  missing
0            AFG              71     16969    16898
164          OSS              71     16969    16898
152          NAC              71     16969    16898
153          NAM              71     16969    16898
154          NER              71     16969    16898
..           ...             ...       ...      ...
84           HND              71     16969    16898
85           HPC              71     16969    16898
86           HRV              71     16969    16898
87           HTI              71     16969    16898
238          ZWE              71     16969    16898

[239 rows x 4 columns]

The results show that all countries have at least some Governance indicators available (num_indicators > 0), confirming that there is data coverage for all countries in the ESG dataset.

<div style="background-color:#EAF4EC; padding:16px; border-radius:10px;">

<h2 style="color:#2F6F4E; margin-bottom:5px; font-size:20px;">
17 Governance Indicators for the EU27 available

In [20]:
gov_codes17 = ["NY.GDP.MKTP.KD.ZG","IT.NET.USER.ZS","SG.GEN.PARL.ZS","SL.TLF.CACT.FM.ZS","SE.ENR.PRSC.FM.ZS","SP.UWT.TFRT","GE.EST","RQ.EST","SD.ESR.PERF.XQ","VA.EST","IP.PAT.RESD","GB.XPD.RSDV.GD.ZS","IP.JRN.ARTC.SC","CC.EST","SM.POP.NETM","PV.EST","RL.EST"]

In [21]:
esg_gov17 = esg_data[esg_data["Indicator Code"].isin(gov_codes17)].copy()

In [22]:
print("Indicators:", esg_gov17["Indicator Code"].nunique())
print("Total lines:", len(esg_gov17))
print(sorted(esg_gov17["Indicator Code"].unique()))

Indicators: 17
Total lines: 4063
['CC.EST', 'GB.XPD.RSDV.GD.ZS', 'GE.EST', 'IP.JRN.ARTC.SC', 'IP.PAT.RESD', 'IT.NET.USER.ZS', 'NY.GDP.MKTP.KD.ZG', 'PV.EST', 'RL.EST', 'RQ.EST', 'SD.ESR.PERF.XQ', 'SE.ENR.PRSC.FM.ZS', 'SG.GEN.PARL.ZS', 'SL.TLF.CACT.FM.ZS', 'SM.POP.NETM', 'SP.UWT.TFRT', 'VA.EST']

Filter by EU-27 Countries

In [23]:
esg_gov17_eu = esg_gov17[esg_gov17["Country Code"].isin(EU27_ISO3)].copy()

In [24]:
print("Countries:", esg_gov17_eu["Country Code"].nunique())
print(sorted(esg_gov17_eu["Country Code"].unique()))

Countries: 27
['AUT', 'BEL', 'BGR', 'CYP', 'CZE', 'DEU', 'DNK', 'ESP', 'EST', 'FIN', 'FRA', 'GRC', 'HRV', 'HUN', 'IRL', 'ITA', 'LTU', 'LUX', 'LVA', 'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'SWE']

In [25]:
esg_gov17_eu.to_csv("../data/processed/esg_gov17_eu27.csv", index=False)